web:
  build: .
  working_dir: /data
  command: python main.py
  links:
    - 503cb8c672c8
  volumes:
    - .:/data
  ports:
    - "8888:8888"

db:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: mudar123
  ports:
    - "3306:3306"
